/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FindClinicsRouteImport } from './routes/find-clinics'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardTreatmentJourneyRouteImport } from './routes/_authenticated/dashboard/treatment-journey'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as AuthenticatedDashboardSavedClinicsRouteImport } from './routes/_authenticated/dashboard/saved-clinics'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard/profile'
import { Route as AuthenticatedDashboardMyReviewsRouteImport } from './routes/_authenticated/dashboard/my-reviews'
import { Route as AuthenticatedDashboardCommunityRouteImport } from './routes/_authenticated/dashboard/community'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FindClinicsRoute = FindClinicsRouteImport.update({
  id: '/find-clinics',
  path: '/find-clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardTreatmentJourneyRoute =
  AuthenticatedDashboardTreatmentJourneyRouteImport.update({
    id: '/dashboard/treatment-journey',
    path: '/dashboard/treatment-journey',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSavedClinicsRoute =
  AuthenticatedDashboardSavedClinicsRouteImport.update({
    id: '/dashboard/saved-clinics',
    path: '/dashboard/saved-clinics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/dashboard/profile',
    path: '/dashboard/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardMyReviewsRoute =
  AuthenticatedDashboardMyReviewsRouteImport.update({
    id: '/dashboard/my-reviews',
    path: '/dashboard/my-reviews',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardCommunityRoute =
  AuthenticatedDashboardCommunityRouteImport.update({
    id: '/dashboard/community',
    path: '/dashboard/community',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/find-clinics': typeof FindClinicsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/community': typeof AuthenticatedDashboardCommunityRoute
  '/dashboard/my-reviews': typeof AuthenticatedDashboardMyReviewsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/saved-clinics': typeof AuthenticatedDashboardSavedClinicsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/treatment-journey': typeof AuthenticatedDashboardTreatmentJourneyRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/find-clinics': typeof FindClinicsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard/community': typeof AuthenticatedDashboardCommunityRoute
  '/dashboard/my-reviews': typeof AuthenticatedDashboardMyReviewsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/saved-clinics': typeof AuthenticatedDashboardSavedClinicsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/treatment-journey': typeof AuthenticatedDashboardTreatmentJourneyRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/find-clinics': typeof FindClinicsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard/community': typeof AuthenticatedDashboardCommunityRoute
  '/_authenticated/dashboard/my-reviews': typeof AuthenticatedDashboardMyReviewsRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/saved-clinics': typeof AuthenticatedDashboardSavedClinicsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/treatment-journey': typeof AuthenticatedDashboardTreatmentJourneyRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/community'
    | '/find-clinics'
    | '/forgot-password'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard/community'
    | '/dashboard/my-reviews'
    | '/dashboard/profile'
    | '/dashboard/saved-clinics'
    | '/dashboard/settings'
    | '/dashboard/treatment-journey'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/community'
    | '/find-clinics'
    | '/forgot-password'
    | '/reset-password'
    | '/sitemap.xml'
    | '/dashboard/community'
    | '/dashboard/my-reviews'
    | '/dashboard/profile'
    | '/dashboard/saved-clinics'
    | '/dashboard/settings'
    | '/dashboard/treatment-journey'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/community'
    | '/find-clinics'
    | '/forgot-password'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/dashboard/community'
    | '/_authenticated/dashboard/my-reviews'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/saved-clinics'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/treatment-journey'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  FindClinicsRoute: typeof FindClinicsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-clinics': {
      id: '/find-clinics'
      path: '/find-clinics'
      fullPath: '/find-clinics'
      preLoaderRoute: typeof FindClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/treatment-journey': {
      id: '/_authenticated/dashboard/treatment-journey'
      path: '/dashboard/treatment-journey'
      fullPath: '/dashboard/treatment-journey'
      preLoaderRoute: typeof AuthenticatedDashboardTreatmentJourneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/saved-clinics': {
      id: '/_authenticated/dashboard/saved-clinics'
      path: '/dashboard/saved-clinics'
      fullPath: '/dashboard/saved-clinics'
      preLoaderRoute: typeof AuthenticatedDashboardSavedClinicsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/my-reviews': {
      id: '/_authenticated/dashboard/my-reviews'
      path: '/dashboard/my-reviews'
      fullPath: '/dashboard/my-reviews'
      preLoaderRoute: typeof AuthenticatedDashboardMyReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/community': {
      id: '/_authenticated/dashboard/community'
      path: '/dashboard/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof AuthenticatedDashboardCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardCommunityRoute: typeof AuthenticatedDashboardCommunityRoute
  AuthenticatedDashboardMyReviewsRoute: typeof AuthenticatedDashboardMyReviewsRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardSavedClinicsRoute: typeof AuthenticatedDashboardSavedClinicsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardTreatmentJourneyRoute: typeof AuthenticatedDashboardTreatmentJourneyRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardCommunityRoute: AuthenticatedDashboardCommunityRoute,
  AuthenticatedDashboardMyReviewsRoute: AuthenticatedDashboardMyReviewsRoute,
  AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
  AuthenticatedDashboardSavedClinicsRoute:
    AuthenticatedDashboardSavedClinicsRoute,
  AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
  AuthenticatedDashboardTreatmentJourneyRoute:
    AuthenticatedDashboardTreatmentJourneyRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  FindClinicsRoute: FindClinicsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
