/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as FindClinicsRouteImport } from './routes/find-clinics'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as ClinicsRouteImport } from './routes/clinics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ClinicsClinicIdRouteImport } from './routes/clinics.$clinicId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminImportRouteImport } from './routes/admin/import'
import { Route as AdminDirectoryRouteImport } from './routes/admin/directory'
import { Route as AdminCommunityRouteImport } from './routes/admin/community'
import { Route as AdminClinicsRouteImport } from './routes/admin/clinics'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardTreatmentJourneyRouteImport } from './routes/_authenticated/dashboard/treatment-journey'
import { Route as AuthenticatedDashboardSettingsRouteImport } from './routes/_authenticated/dashboard/settings'
import { Route as AuthenticatedDashboardSavedClinicsRouteImport } from './routes/_authenticated/dashboard/saved-clinics'
import { Route as AuthenticatedDashboardProfileRouteImport } from './routes/_authenticated/dashboard/profile'
import { Route as AuthenticatedDashboardMyReviewsRouteImport } from './routes/_authenticated/dashboard/my-reviews'
import { Route as AuthenticatedDashboardCommunityRouteImport } from './routes/_authenticated/dashboard/community'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FindClinicsRoute = FindClinicsRouteImport.update({
  id: '/find-clinics',
  path: '/find-clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsRoute = ClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ClinicsClinicIdRoute = ClinicsClinicIdRouteImport.update({
  id: '/$clinicId',
  path: '/$clinicId',
  getParentRoute: () => ClinicsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDirectoryRoute = AdminDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCommunityRoute = AdminCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClinicsRoute = AdminClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardTreatmentJourneyRoute =
  AuthenticatedDashboardTreatmentJourneyRouteImport.update({
    id: '/dashboard/treatment-journey',
    path: '/dashboard/treatment-journey',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSettingsRoute =
  AuthenticatedDashboardSettingsRouteImport.update({
    id: '/dashboard/settings',
    path: '/dashboard/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardSavedClinicsRoute =
  AuthenticatedDashboardSavedClinicsRouteImport.update({
    id: '/dashboard/saved-clinics',
    path: '/dashboard/saved-clinics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardProfileRoute =
  AuthenticatedDashboardProfileRouteImport.update({
    id: '/dashboard/profile',
    path: '/dashboard/profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardMyReviewsRoute =
  AuthenticatedDashboardMyReviewsRouteImport.update({
    id: '/dashboard/my-reviews',
    path: '/dashboard/my-reviews',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardCommunityRoute =
  AuthenticatedDashboardCommunityRouteImport.update({
    id: '/dashboard/community',
    path: '/dashboard/community',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/clinics': typeof ClinicsRouteWithChildren
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/find-clinics': typeof FindClinicsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal': typeof LegalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/clinics/$clinicId': typeof ClinicsClinicIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/community': typeof AuthenticatedDashboardCommunityRoute
  '/dashboard/my-reviews': typeof AuthenticatedDashboardMyReviewsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/saved-clinics': typeof AuthenticatedDashboardSavedClinicsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/treatment-journey': typeof AuthenticatedDashboardTreatmentJourneyRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/clinics': typeof ClinicsRouteWithChildren
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/find-clinics': typeof FindClinicsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal': typeof LegalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/clinics/$clinicId': typeof ClinicsClinicIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard/community': typeof AuthenticatedDashboardCommunityRoute
  '/dashboard/my-reviews': typeof AuthenticatedDashboardMyReviewsRoute
  '/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/dashboard/saved-clinics': typeof AuthenticatedDashboardSavedClinicsRoute
  '/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/dashboard/treatment-journey': typeof AuthenticatedDashboardTreatmentJourneyRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/clinics': typeof ClinicsRouteWithChildren
  '/community': typeof CommunityRoute
  '/contact': typeof ContactRoute
  '/find-clinics': typeof FindClinicsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal': typeof LegalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/reviews': typeof ReviewsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/community': typeof AdminCommunityRoute
  '/admin/directory': typeof AdminDirectoryRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/users': typeof AdminUsersRoute
  '/clinics/$clinicId': typeof ClinicsClinicIdRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/dashboard/community': typeof AuthenticatedDashboardCommunityRoute
  '/_authenticated/dashboard/my-reviews': typeof AuthenticatedDashboardMyReviewsRoute
  '/_authenticated/dashboard/profile': typeof AuthenticatedDashboardProfileRoute
  '/_authenticated/dashboard/saved-clinics': typeof AuthenticatedDashboardSavedClinicsRoute
  '/_authenticated/dashboard/settings': typeof AuthenticatedDashboardSettingsRoute
  '/_authenticated/dashboard/treatment-journey': typeof AuthenticatedDashboardTreatmentJourneyRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/clinics'
    | '/community'
    | '/contact'
    | '/find-clinics'
    | '/forgot-password'
    | '/legal'
    | '/reset-password'
    | '/resources'
    | '/reviews'
    | '/sitemap.xml'
    | '/admin/clinics'
    | '/admin/community'
    | '/admin/directory'
    | '/admin/import'
    | '/admin/reviews'
    | '/admin/users'
    | '/clinics/$clinicId'
    | '/admin/'
    | '/dashboard/community'
    | '/dashboard/my-reviews'
    | '/dashboard/profile'
    | '/dashboard/saved-clinics'
    | '/dashboard/settings'
    | '/dashboard/treatment-journey'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/clinics'
    | '/community'
    | '/contact'
    | '/find-clinics'
    | '/forgot-password'
    | '/legal'
    | '/reset-password'
    | '/resources'
    | '/reviews'
    | '/sitemap.xml'
    | '/admin/clinics'
    | '/admin/community'
    | '/admin/directory'
    | '/admin/import'
    | '/admin/reviews'
    | '/admin/users'
    | '/clinics/$clinicId'
    | '/admin'
    | '/dashboard/community'
    | '/dashboard/my-reviews'
    | '/dashboard/profile'
    | '/dashboard/saved-clinics'
    | '/dashboard/settings'
    | '/dashboard/treatment-journey'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/clinics'
    | '/community'
    | '/contact'
    | '/find-clinics'
    | '/forgot-password'
    | '/legal'
    | '/reset-password'
    | '/resources'
    | '/reviews'
    | '/sitemap.xml'
    | '/admin/clinics'
    | '/admin/community'
    | '/admin/directory'
    | '/admin/import'
    | '/admin/reviews'
    | '/admin/users'
    | '/clinics/$clinicId'
    | '/admin/'
    | '/_authenticated/dashboard/community'
    | '/_authenticated/dashboard/my-reviews'
    | '/_authenticated/dashboard/profile'
    | '/_authenticated/dashboard/saved-clinics'
    | '/_authenticated/dashboard/settings'
    | '/_authenticated/dashboard/treatment-journey'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ClinicsRoute: typeof ClinicsRouteWithChildren
  CommunityRoute: typeof CommunityRoute
  ContactRoute: typeof ContactRoute
  FindClinicsRoute: typeof FindClinicsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LegalRoute: typeof LegalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  ReviewsRoute: typeof ReviewsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-clinics': {
      id: '/find-clinics'
      path: '/find-clinics'
      fullPath: '/find-clinics'
      preLoaderRoute: typeof FindClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics': {
      id: '/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof ClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/clinics/$clinicId': {
      id: '/clinics/$clinicId'
      path: '/$clinicId'
      fullPath: '/clinics/$clinicId'
      preLoaderRoute: typeof ClinicsClinicIdRouteImport
      parentRoute: typeof ClinicsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/directory': {
      id: '/admin/directory'
      path: '/directory'
      fullPath: '/admin/directory'
      preLoaderRoute: typeof AdminDirectoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/community': {
      id: '/admin/community'
      path: '/community'
      fullPath: '/admin/community'
      preLoaderRoute: typeof AdminCommunityRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/clinics': {
      id: '/admin/clinics'
      path: '/clinics'
      fullPath: '/admin/clinics'
      preLoaderRoute: typeof AdminClinicsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/treatment-journey': {
      id: '/_authenticated/dashboard/treatment-journey'
      path: '/dashboard/treatment-journey'
      fullPath: '/dashboard/treatment-journey'
      preLoaderRoute: typeof AuthenticatedDashboardTreatmentJourneyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/settings': {
      id: '/_authenticated/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof AuthenticatedDashboardSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/saved-clinics': {
      id: '/_authenticated/dashboard/saved-clinics'
      path: '/dashboard/saved-clinics'
      fullPath: '/dashboard/saved-clinics'
      preLoaderRoute: typeof AuthenticatedDashboardSavedClinicsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/profile': {
      id: '/_authenticated/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof AuthenticatedDashboardProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/my-reviews': {
      id: '/_authenticated/dashboard/my-reviews'
      path: '/dashboard/my-reviews'
      fullPath: '/dashboard/my-reviews'
      preLoaderRoute: typeof AuthenticatedDashboardMyReviewsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/community': {
      id: '/_authenticated/dashboard/community'
      path: '/dashboard/community'
      fullPath: '/dashboard/community'
      preLoaderRoute: typeof AuthenticatedDashboardCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardCommunityRoute: typeof AuthenticatedDashboardCommunityRoute
  AuthenticatedDashboardMyReviewsRoute: typeof AuthenticatedDashboardMyReviewsRoute
  AuthenticatedDashboardProfileRoute: typeof AuthenticatedDashboardProfileRoute
  AuthenticatedDashboardSavedClinicsRoute: typeof AuthenticatedDashboardSavedClinicsRoute
  AuthenticatedDashboardSettingsRoute: typeof AuthenticatedDashboardSettingsRoute
  AuthenticatedDashboardTreatmentJourneyRoute: typeof AuthenticatedDashboardTreatmentJourneyRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardCommunityRoute: AuthenticatedDashboardCommunityRoute,
  AuthenticatedDashboardMyReviewsRoute: AuthenticatedDashboardMyReviewsRoute,
  AuthenticatedDashboardProfileRoute: AuthenticatedDashboardProfileRoute,
  AuthenticatedDashboardSavedClinicsRoute:
    AuthenticatedDashboardSavedClinicsRoute,
  AuthenticatedDashboardSettingsRoute: AuthenticatedDashboardSettingsRoute,
  AuthenticatedDashboardTreatmentJourneyRoute:
    AuthenticatedDashboardTreatmentJourneyRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminClinicsRoute: typeof AdminClinicsRoute
  AdminCommunityRoute: typeof AdminCommunityRoute
  AdminDirectoryRoute: typeof AdminDirectoryRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminClinicsRoute: AdminClinicsRoute,
  AdminCommunityRoute: AdminCommunityRoute,
  AdminDirectoryRoute: AdminDirectoryRoute,
  AdminImportRoute: AdminImportRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ClinicsRouteChildren {
  ClinicsClinicIdRoute: typeof ClinicsClinicIdRoute
}

const ClinicsRouteChildren: ClinicsRouteChildren = {
  ClinicsClinicIdRoute: ClinicsClinicIdRoute,
}

const ClinicsRouteWithChildren =
  ClinicsRoute._addFileChildren(ClinicsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ClinicsRoute: ClinicsRouteWithChildren,
  CommunityRoute: CommunityRoute,
  ContactRoute: ContactRoute,
  FindClinicsRoute: FindClinicsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LegalRoute: LegalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  ReviewsRoute: ReviewsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
